{
    "openapi": "3.1.0",
    "info": {
        "title": "FlowPay API",
        "version": "2.0.0-alpha.4",
        "description": {
            "$ref": "docs/general.md"
        },
        "termsOfService": "https://developer.flowpay.it/tos",
        "license": {
            "name": "FlowPay SRL",
            "url": "https://developer.flowpay.it/tos"
        },
        "x-logo": {
            "url": "https://images.flowpay.it/logo",
            "altText": "FlowPay"
        },
        "contact": {
            "name": "API Support",
            "url": "https://developer.flowpay.it",
            "email": "api-support@flowpay.it"
        },
        "x-json-schema-faker": {
            "locale": "it-IT",
            "omitNulls": true,
            "fillProperties": true,
            "reuseProperties": true
        }
    },
    "servers": [
        {
            "url": "https://api.flowpay.it/v2",
            "description": "Production server (Not implementend)"
        },
        {
            "url": "https://mock.flowpay.it/v2",
            "description": "Mock server"
        },
        {
            "url": "https://sandbox.{customerID}.flowpay.it/v2",
            "description": "Customer-assigned sandbox server",
            "variables": {
                "customerID": {
                    "default": "00000000-00000000-00000000-00000000",
                    "description": "Unique customer identifier assigned after contract signature"
                }
            }
        },
        {
            "url": "http://localhost:5002",
            "description": "Debug"
        }
    ],
    "components": {
        "securitySchemes": {
            "oAuth2": {
                "type": "oauth2",
                "description": "OAuth2 flow",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "/openid/authenticate",
                        "tokenUrl": "/oauth/token",
                        "refreshUrl": "/oauth/token",
                        "scopes": {
                            "accounts:read": "Allow to read accounts",
                            "accounts:write": "Allow to mediate accounts creation and open banking consent renewal",
                            "invoices:read": "Allow to read invoices",
                            "invoices:write": "Allow to create invoices and manage lifecycle",
                            "bills:read": "Allow to read bills",
                            "bills:write": "Allow to create bills and manage lifecycle",
                            "constructions:read": "Allow to read information about construction sites",
                            "constructions:write": "Allow to create construction sites and manage the lifecycle",
                            "openid": "Allow to read user profile",
                            "pagopa:read": "Allow to retrieve users' PagoPA payment notices",
                            "pagopa:write": "Allow to create PagoPA payment notices",
                            "transfers:read": "Allow to read transfers",
                            "transfers:write": "Allow to create transfers and manage lifecycle",
                            "wallet:`document_type`": "Allow to manage wallet for the specified use case"
                        }
                    },
                    "clientCredentials": {
                        "tokenUrl": "/oauth/token",
                        "scopes": {
                            "ade": "Allow to interact with Agenzia delle Entrate services",
                            "accounts:read": "Allow to read accounts",
                            "accounts:write": "Allow to mediate accounts creation and open banking consent renewal",
                            "invoices:read": "Allow to read invoices",
                            "invoices:write": "Allow to create invoices and manage lifecycle",
                            "bills:read": "Allow to read bills",
                            "bills:write": "Allow to create bills and manage lifecycle",
                            "constructions:read": "Allow to read information about construction sites",
                            "constructions:write": "Allow to create construction sites and manage the lifecycle",
                            "openid": "Allow to read user profile",
                            "pagopa:read": "Allow to retrieve users' PagoPA payment notices",
                            "pagopa:write": "Allow to create PagoPA payment notices",
                            "transfers:read": "Allow to read transfers",
                            "transfers:write": "Allow to create transfers and manage lifecycle",
                            "wallet:`document_type`": "Allow to manage wallet for the specified use case"
                        }
                    }
                }
            }
        }
    },
    "webhooks": {
        "AIS consent status": {
            "post": {
                "summary": "AIS consent status",
                "description": "Notify the status of the account information service (AIS) ",
                "operationId": "AISConsentStatus",
                "security": [],
                "tags": [
                    "Accounts",
                    "Webhooks"
                ]
            }
        }
    },
    "tags": [
        {
            "name": "Accounts",
            "description": "Manage accounts"
        },
        {
            "name": "Authentication",
            "description": "Manage authentication"
        },
        {
            "name": "Banks",
            "description": "Banks informations"
        },
        {
            "name": "Bulk",
            "description": {
                "$ref": "docs/bulk_lifecycle.md"
            }
        },
        {
            "name": "Chain",
            "description": {
                "$ref": "docs/chain_lifecycle.md"
            }
        },
        {
            "name": "Checkout",
            "description": "This endpoint allows managing checkout sessions any document client has access to"
        },
        {
            "name": "Construction",
            "description": "Manage construction sites and related entities lifecycle"
        },
        {
            "name": "Fee",
            "description": {
                "$ref": "docs/fee_description.md"
            }
        },
        {
            "name": "Invoices",
            "description": {
                "$ref": "docs/invoice_lifecycle.md"
            }
        },
        {
            "name": "KYC",
            "description": {
                "$ref": "docs/kyc_description.md"
            }
        },
        {
            "name": "pagoPA",
            "description": {
                "$ref": "docs/pagopa_lifecycle.md"
            }
        },
        {
            "name": "Payments",
            "description": "Access to payments initiated by FlowPay"
        },
        {
            "name": "Transactions",
            "description": "Endpoint for retrieving transactions collected with AIS consent"
        },
        {
            "name": "Transfers",
            "description": "Lifecycle-free documents"
        },
        {
            "name": "Webhooks",
            "description": "Manage webhooks"
        },
        {
            "name": "Documents",
            "description": "CRUD operations on documents"
        }
    ],
    "paths": {
        "/oauth/token": {
            "post": {
                "summary": "Get an access token or refresh an existing one",
                "description": "Get an access token or refresh an existing one",
                "operationId": "GetAccessToken",
                "tags": [
                    "Authentication"
                ],
                "security": []
            }
        },
        "/oauth/token/info": {
            "post": {
                "summary": "Get information about the token",
                "description": "Get information about the token",
                "operationId": "GetTokenInfo",
                "security": [],
                "tags": [
                    "Authentication"
                ]
            }
        },
        "/accounts": {
            "get": {
                "summary": "Get the list of accounts",
                "description": "Get the list of accounts associated to the token",
                "operationId": "getAccounts",
                "security": [
                    {
                        "oAuth2": [
                            "accounts:read"
                        ]
                    }
                ],
                "tags": [
                    "Accounts"
                ]
            },
            "post": {
                "summary": "Create account consent session",
                "description": "Create a new session to allow an user to grant consent to FlowPay to access his accounts for AIS service.<br>Clients can use this endpoint to create a new session to allow an user to grant consent to FlowPay to access his accounts for AIS service.",
                "operationId": "createAisConsentSession",
                "security": [
                    {
                        "oAuth2": [
                            "accounts:write"
                        ]
                    }
                ],
                "callbacks": {
                    "ok": {
                        "/": {
                            "get": {
                                "summary": "Consent correctly granted",
                                "description": "Redirect URL to be used by FlowPay to notify the client that user has granted consent to FlowPay to access his accounts for AIS service. <br> After the user has granted consent to FlowPay to access his accounts for AIS service, the bank will redirect to FlowPay server to notify the result of the operation, FlowPay will then redirect to the client to notify the result of the operation.<br> Use this redirect URL to manage user experience, for example[...]",
                                "operationId": "aisOkConsentSessionCallback",
                                "security": []
                            }
                        }
                    },
                    "ko": {
                        "/": {
                            "get": {
                                "summary": "Some error occured",
                                "description": "Redirect URL to be used by FlowPay to notify the client that user has not granted consent to FlowPay to access his accounts for AIS service. <br>After user redirection to FlowPay server, FlowPay will then redirect to the client to notify the result of the operation.<br> Use this redirect URL to manage user experience.",
                                "operationId": "aisKoConsentSessionCallback",
                                "security": []
                            }
                        }
                    }
                },
                "tags": [
                    "Accounts"
                ]
            }
        },
        "/accounts/{accountID}": {
            "get": {
                "summary": "Get account details",
                "description": "Retrieve details of a specific account",
                "operationId": "getAccount",
                "security": [
                    {
                        "oAuth2": [
                            "accounts:read"
                        ]
                    }
                ],
                "tags": [
                    "Accounts"
                ]
            }
        },
        "/banks": {
            "get": {
                "summary": "Get banks",
                "description": "Retrieve the list of banks supported by FlowPay",
                "operationId": "getBanks",
                "security": [],
                "tags": [
                    "Banks"
                ]
            }
        },
        "/banks/{id}": {
            "get": {
                "summary": "Get bank details",
                "description": "Retrieve details of a specific bank",
                "operationId": "getBank",
                "security": [],
                "tags": [
                    "Banks"
                ]
            }
        },
        "/bulk": {
            "post": {
                "summary": "Create bulk document",
                "description": "Create a new bulk document. This endpoint allows to specificy a dictionary of fingerprints to be linked to the bulk payment, each property name is the document type. <br> Returns the bulk document created with a new fingerprint.",
                "operationId": "createBulkPayment",
                "security": [
                    {
                        "oAuth2": []
                    }
                ],
                "tags": [
                    "Bulk"
                ]
            },
            "get": {
                "summary": "List bulk documents",
                "description": "List all bulk documents according to the specified filters. <br> Returns a paginated list of bulk documents.",
                "operationId": "listBulkPayments",
                "security": [
                    {
                        "oAuth2": []
                    }
                ],
                "tags": [
                    "Bulk"
                ]
            }
        },
        "/bulk/{fingerprint}": {
            "get": {
                "summary": "Get document details",
                "description": "Get bulk document details by ID",
                "operationId": "getBulkPayment",
                "security": [
                    {
                        "oAuth2": []
                    }
                ],
                "tags": [
                    "Bulk"
                ]
            },
            "delete": {
                "summary": "Delete bulk payment",
                "description": "Delete bulk payment by ID.<br>Deleting a bulk payment will not delete the linked documents.",
                "operationId": "deleteBulkPayment",
                "security": [
                    {
                        "oAuth2": []
                    }
                ],
                "tags": [
                    "Bulk"
                ]
            }
        },
        "/chain": {
            "post": {
                "summary": "Create chain document",
                "description": "Create a new chain document. This endpoint allows to specify the fingerprint of the document that will be paid and the trigger document for that payment, along with their type.",
                "operationId": "createChainPayment",
                "security": [
                    {
                        "oAuth2": []
                    }
                ],
                "tags": [
                    "Chain"
                ]
            },
            "get": {
                "summary": "List chain documents",
                "description": "List all chain documents according to the specified filters. <br> Returns a paginated list of chain documents.",
                "operationId": "listChainPayments",
                "security": [
                    {
                        "oAuth2": []
                    }
                ],
                "tags": [
                    "Chain"
                ]
            }
        },
        "/chain/{fingerprint}": {
            "get": {
                "summary": "Get document details",
                "description": "Get bulk document details by ID",
                "operationId": "getChainPayment",
                "security": [
                    {
                        "oAuth2": []
                    }
                ],
                "tags": [
                    "Chain"
                ]
            }
        },
        "/checkout": {
            "post": {
                "summary": "Create checkout",
                "description": "This endpoint allows to create a new checkout specifying the document to be paid. <br> If the payment needs to be authorized by the user, the response will contain a link to be used to redirect the user to FlowPay payment page.",
                "operationId": "createCheckout",
                "security": [
                    {
                        "oAuth2": []
                    }
                ],
                "tags": [
                    "Checkout"
                ]
            }
        },
        "/checkout/{code}": {
            "get": {
                "summary": "Get checkout details",
                "description": "Retrieve details of a specific checkout",
                "operationId": "getCheckout",
                "security": [
                    {
                        "oAuth2": [
                            "checkout:read"
                        ]
                    }
                ],
                "tags": [
                    "Checkout"
                ]
            },
            "delete": {
                "summary": "Delete checkout",
                "description": "Allows to delete a checkout. <br> This endpoint can be used to delete a checkout that has not been paid yet. <br> If the checkout has been paid, it cannot be deleted and this endpoint will return an error.",
                "operationId": "deleteCheckout",
                "security": [
                    {
                        "oAuth2": []
                    }
                ],
                "tags": [
                    "Checkout"
                ]
            }
        },
        "/creditNotes": {
            "post": {
                "summary": "Create credit note",
                "description": "Create a credit note to be paid by a customer",
                "operationId": "createCreditNote",
                "security": [
                    {
                        "oAuth2": [
                            "invoice:read"
                        ]
                    }
                ],
                "tags": [
                    "Invoices",
                    "Documents"
                ]
            },
            "get": {
                "summary": "List credit notes",
                "description": "Retrieve a list of credit notes",
                "operationId": "getCreditNotes",
                "security": [
                    {
                        "oAuth2": [
                            "invoice:read"
                        ]
                    }
                ],
                "tags": [
                    "Invoices",
                    "Documents"
                ]
            }
        },
        "/creditNotes/{fingerprint}": {
            "get": {
                "summary": "Get credit note details",
                "description": "Retrieve a credit note details by its fingerprint",
                "operationId": "getCreditNote",
                "security": [
                    {
                        "oAuth2": [
                            "invoice:read"
                        ]
                    }
                ],
                "tags": [
                    "Invoices",
                    "Documents"
                ]
            },
            "delete": {
                "summary": "Delete credit note",
                "description": "Delete a credit note by its fingerprint",
                "operationId": "deleteCreditNote",
                "security": [
                    {
                        "oAuth2": [
                            "invoice:write"
                        ]
                    }
                ],
                "tags": [
                    "Invoices",
                    "Documents"
                ]
            }
        },
        "/constructions/contracts": {
            "post": {
                "tags": [
                    "Construction"
                ],
                "operationId": "addSiteWorker",
                "summary": "Add worker to site",
                "description": "This endpoint manages the association between a site and a worker. Is not mandatory for the worker to be registered on FlowPay. This request must be authorized by the site owner, then the worker will be able to call the [PATCH] `/constructions/contracts/{identifier}` endpoint to complete the handshake.",
                "security": [
                    {
                        "oAuth2": [
                            "construction:write"
                        ]
                    }
                ]
            },
            "get": {
                "tags": [
                    "Construction"
                ],
                "operationId": "getWorkers",
                "summary": "List workers",
                "description": "Allows to retrieve a list of workers associated to the customer.",
                "security": [
                    {
                        "oAuth2": [
                            "construction:read"
                        ]
                    }
                ]
            }
        },
        "/constructions/contracts/{identifier}": {
            "patch": {
                "summary": "Accept assignment",
                "description": "This endpoint allows workers to accept the assignment to a site. The request must be authorized by the worker.",
                "operationId": "acceptSiteAssignment",
                "security": [
                    {
                        "oAuth2": [
                            "construction:write"
                        ]
                    }
                ],
                "tags": [
                    "Construction"
                ]
            },
            "delete": {
                "summary": "Contract withdrawal",
                "description": "This endpoint allows workers and site owners to withdraw from a contract. The request must be authorized by the worker or the site owner.",
                "operationId": "withdrawFromSite",
                "security": [
                    {
                        "oAuth2": [
                            "construction:write"
                        ]
                    }
                ],
                "tags": [
                    "Construction"
                ]
            }
        },
        "/constructions/sites": {
            "post": {
                "tags": [
                    "Construction"
                ],
                "operationId": "createConstructionSite",
                "summary": "Open a new site",
                "description": "Allows to define a new site to be managed with FlowPay",
                "security": [
                    {
                        "oAuth2": [
                            "authorization_code"
                        ]
                    }
                ]
            },
            "get": {
                "tags": [
                    "Construction"
                ],
                "operationId": "getConstructionSites",
                "summary": "List sites",
                "description": "Allows to retrieve a list of sites managed by the customer",
                "security": [
                    {
                        "oAuth2": [
                            "construction:read"
                        ]
                    }
                ]
            }
        },
        "/constructions/sites/{identifier}": {
            "get": {
                "tags": [
                    "Construction"
                ],
                "operationId": "getConstructionSite",
                "summary": "Get site details",
                "description": "Allows to retrieve details of a specific site",
                "security": [
                    {
                        "oAuth2": [
                            "construction:read"
                        ]
                    }
                ]
            }
        },
        "/constructions/sites/{identifier}/cashout": {
            "post": {
                "operationId": "cashout",
                "summary": "Cashout",
                "description": "Allows to cashout residual money from a site. <br> The request acts on the site wallet owned by the owner of the oauth token used to call the endpoint.",
                "security": [
                    {
                        "oAuth2": [
                            "construction:write",
                            "wallet:construction"
                        ]
                    }
                ]
            }
        },
        "/constructions/sites/{identifier}/quote": {
            "post": {
                "tags": [
                    "Construction"
                ],
                "operationId": "createQuote",
                "summary": "Create quote",
                "description": "Allows to create a new quote for a specific site, useful to credit site owner wallet with the amount needed to start the site operations. <br> The request must be authorized by the site owner.",
                "security": [
                    {
                        "oAuth2": [
                            "construction:write",
                            "wallet:construction"
                        ]
                    }
                ]
            },
            "get": {
                "tags": [
                    "Construction"
                ],
                "operationId": "getQuotes",
                "summary": "List quotes",
                "description": "Allows to retrieve a list of quotes for a specific site",
                "security": [
                    {
                        "oAuth2": [
                            "construction:read",
                            "wallet:construction"
                        ]
                    }
                ]
            }
        },
        "/constructions/progress": {
            "post": {
                "summary": "Register work progress",
                "description": "You can register work progress by passing a list of the invoices previously uploaded using the `/invoices` endpoint. <br> The request must be authorized by the worker. <br> Each invoice between site owner and worker will be linked to a new site-related document.<br> Each invoice between the worker and their suppliers will be linked to a new document.<br><b>Note: The sum of the worker-to-customer invoices must be at least equal to the sum of the supplier-to-worker [...]",
                "operationId": "registerWorkProgress",
                "security": [
                    {
                        "oAuth2": [
                            "construction:write"
                        ]
                    }
                ],
                "tags": [
                    "Construction"
                ]
            },
            "get": {
                "summary": "List work progress",
                "description": "Allows to retrieve a list of work progress registered by the worker",
                "operationId": "getWorkProgress",
                "security": [
                    {
                        "oAuth2": [
                            "construction:read"
                        ]
                    }
                ],
                "tags": [
                    "Construction"
                ]
            }
        },
        "/constructions/progress/{identifier}": {
            "get": {
                "summary": "Get work progress details",
                "description": "Allows to retrieve details of a specific work progress",
                "operationId": "getWorkProgressDetails",
                "security": [
                    {
                        "oAuth2": [
                            "construction:read"
                        ]
                    }
                ],
                "tags": [
                    "Construction"
                ]
            }
        },
        "/fee": {
            "get": {
                "summary": "List fees",
                "description": "Retrieve the list of fees applied to the customer for the services provided by the client",
                "operationId": "getFees",
                "security": [
                    {
                        "oAuth2": [
                            "fees:read"
                        ]
                    }
                ],
                "tags": [
                    "Fee"
                ]
            }
        },
        "/fee/rules": {
            "get": {
                "summary": "List fee rules",
                "operationId": "list_fee_rules",
                "description": "Retrieve a list of fee rules based on query parameters.",
                "security": [
                    {
                        "oAuth2": []
                    }
                ],
                "tags": [
                    "Fee"
                ]
            }
        },
        "/fee/rules/{kind}/{fingerprint}": {
            "get": {
                "summary": "Retrieve fee rules for a document",
                "description": "Retrieve fee rules for a document identified by its type and fingerprint. The response is a mapping of payment methods (e.g., card, sdd, pis) to the corresponding fee rule.",
                "operationId": "getFeeRules",
                "security": [
                    {
                        "oAuth2": []
                    }
                ],
                "tags": [
                    "Fee"
                ]
            }
        },
        "/fee/rules/{kind}/{fingerprint}/{payer}": {
            "get": {
                "summary": "Retrieve fee rule for a specific payer",
                "description": "Retrieve fee rule(s) for a document identified by its type and fingerprint, filtered by the specified payer. Optionally, an 'amount' query parameter can be provided to influence fee calculation.",
                "operationId": "getFeeRuleForPayer",
                "security": [
                    {
                        "oAuth2": []
                    }
                ],
                "tags": [
                    "Fee"
                ]
            }
        },
        "/invoices": {
            "post": {
                "summary": "Create invoice",
                "description": "Create an invoice to be paid by a customer",
                "operationId": "createInvoice",
                "security": [
                    {
                        "oAuth2": [
                            "invoices:write"
                        ]
                    }
                ],
                "tags": [
                    "Invoices",
                    "Documents"
                ]
            },
            "get": {
                "summary": "List invoices",
                "description": "Retrieve invoices list according to the specified filters",
                "operationId": "getInvoices",
                "security": [
                    {
                        "oAuth2": [
                            "invoices:read"
                        ]
                    }
                ],
                "tags": [
                    "Invoices",
                    "Documents"
                ]
            }
        },
        "/invoices/{fingerprint}": {
            "get": {
                "summary": "Get invoice details",
                "description": "Retrieve invoice details by fingerprint",
                "operationId": "getInvoice",
                "security": [
                    {
                        "oAuth2": [
                            "invoices:read"
                        ]
                    }
                ],
                "tags": [
                    "Invoices",
                    "Documents"
                ]
            }
        },
        "/kyc": {
            "post": {
                "summary": "Start KYC",
                "description": "Start KYC process for the current user",
                "operationId": "startKyc",
                "tags": [
                    "KYC"
                ],
                "security": [
                    {
                        "oAuth2": [
                            "kyc"
                        ]
                    }
                ]
            }
        },
        "/kyc/{identifier}": {
            "get": {
                "summary": "Get KYC data",
                "description": "Retrieve KYC data for the specified session",
                "operationId": "getKycStatus",
                "security": [
                    {
                        "oAuth2": [
                            "kyc"
                        ]
                    }
                ],
                "tags": [
                    "KYC"
                ]
            }
        },
        "/pagopa": {
            "post": {
                "summary": "pagoPA payment",
                "description": "Allow to upload a pagoPA payment notice",
                "operationId": "pagopaPayment",
                "security": [
                    {
                        "oAuth2": [
                            "pagopa:write"
                        ]
                    }
                ],
                "tags": [
                    "pagoPA",
                    "Documents"
                ]
            },
            "get": {
                "summary": "pagoPA list",
                "description": "Retrieve pagoPA list according to the specified filters",
                "operationId": "getPagopaList",
                "security": [
                    {
                        "oAuth2": [
                            "pagopa:read"
                        ]
                    }
                ],
                "tags": [
                    "pagoPA",
                    "Documents"
                ]
            }
        },
        "/pagopa/{fingerprint}": {
            "get": {
                "summary": "Get pagoPA details",
                "description": "Retrieve pagoPA details by fingerprint",
                "operationId": "getPagopaDetails",
                "security": [
                    {
                        "oAuth2": [
                            "pagopa:read"
                        ]
                    }
                ],
                "tags": [
                    "pagoPA",
                    "Documents"
                ]
            }
        },
        "/pagopa/{fingerprint}/receipt": {
            "get": {
                "summary": "Get pagoPA receipt",
                "description": "Retrieve pagoPA receipt by fingerprint",
                "operationId": "getPagopaReceipt",
                "security": [
                    {
                        "oAuth2": [
                            "pagopa:read"
                        ]
                    }
                ],
                "tags": [
                    "pagoPA",
                    "Documents"
                ]
            }
        },
        "/payments": {
            "get": {
                "summary": "Get payments",
                "description": "Retrieve payments made through FlowPay",
                "operationId": "getPayments",
                "security": [
                    {
                        "oAuth2": [
                            "payments:read"
                        ]
                    }
                ],
                "tags": [
                    "Payments"
                ]
            }
        },
        "/payments/{paymentID}": {
            "get": {
                "summary": "Get payment details",
                "description": "Retrieve details of a specific payment",
                "operationId": "getPayment",
                "security": [
                    {
                        "oAuth2": [
                            "payments:read"
                        ]
                    }
                ],
                "tags": [
                    "Payments"
                ]
            }
        },
        "/proforma": {
            "post": {
                "summary": "Create proforma invoice",
                "description": "Create a proforma invoice to be paid by a customer",
                "operationId": "createProformaInvoice",
                "security": [
                    {
                        "oAuth2": [
                            "invoice:write"
                        ]
                    }
                ],
                "tags": [
                    "Invoices",
                    "Documents"
                ]
            },
            "get": {
                "summary": "List proforma invoices",
                "description": "Retrieve proforma invoices list according to the specified filters",
                "operationId": "getProformaInvoices",
                "security": [
                    {
                        "oAuth2": [
                            "invoice:read"
                        ]
                    }
                ],
                "tags": [
                    "Invoices",
                    "Documents"
                ]
            }
        },
        "/proforma/{fingerprint}": {
            "get": {
                "summary": "Get proforma details",
                "description": "Retrieve a proforma invoice details",
                "operationId": "getProformaInvoice",
                "security": [
                    {
                        "oAuth2": [
                            "invoice:read"
                        ]
                    }
                ],
                "tags": [
                    "Invoices",
                    "Documents"
                ]
            },
            "delete": {
                "summary": "Delete proforma invoice",
                "description": "Delete a proforma invoice. This operation is allowed only if the proforma invoice is not yet paid",
                "operationId": "deleteProformaInvoice",
                "security": [
                    {
                        "oAuth2": [
                            "invoice:write"
                        ]
                    }
                ],
                "tags": [
                    "Invoices",
                    "Documents"
                ]
            }
        },
        "/transactions": {
            "get": {
                "summary": "Get transactions",
                "description": "Retrieve transactions of a specific account",
                "operationId": "getTransactions",
                "security": [
                    {
                        "oAuth2": [
                            "transactions:read"
                        ]
                    }
                ],
                "tags": [
                    "Transactions"
                ]
            }
        },
        "/transactions/{transactionID}": {
            "get": {
                "summary": "Get transaction details",
                "description": "Retrieve details of a specific transaction.<br>If the transactions has been originated by a payment authorized using FlowPay, the payment details are included in the response, but only if the token used to call the API has the `payment:read` scope.",
                "operationId": "getTransaction",
                "security": [
                    {
                        "oAuth2": [
                            "transactions:read"
                        ]
                    }
                ],
                "tags": [
                    "Transactions"
                ]
            }
        },
        "/transfers": {
            "get": {
                "summary": "Get transfers",
                "description": "Retrieve transfers document list",
                "operationId": "getTransfers",
                "security": [
                    {
                        "oAuth2": [
                            "transfers:read"
                        ]
                    }
                ],
                "tags": [
                    "Transfers"
                ]
            },
            "post": {
                "summary": "Create transfer",
                "description": "Create a new transfer document",
                "operationId": "createTransfer",
                "security": [
                    {
                        "oAuth2": [
                            "transfers:write"
                        ]
                    }
                ],
                "tags": [
                    "Transfers",
                    "Documents"
                ]
            }
        },
        "/transfers/{transferID}": {
            "get": {
                "summary": "Get transfer details",
                "description": "Retrieve transfer document details",
                "operationId": "getTransfer",
                "security": [
                    {
                        "oAuth2": [
                            "transfers:read"
                        ]
                    }
                ],
                "tags": [
                    "Transfers"
                ]
            },
            "delete": {
                "summary": "Delete transfer",
                "description": "Delete a transfer document that has not yet been executed",
                "operationId": "deleteTransfer",
                "security": [
                    {
                        "oAuth2": [
                            "transfers:write"
                        ]
                    }
                ],
                "tags": [
                    "Transfers"
                ]
            }
        }
    }
}